name: Test CI

on:
  push

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["westend"]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Polkadot
        uses: actions/checkout@v2
        with:
          repository: paritytech/polkadot
          path: 'polkadot'
      - name: Srtool build
        id: srtool_build
        uses: ./
        with:
          chain: "{{ matrix.chain }}"
          package: "runtime-${{ matrix.chain }}"
          tag: "nightly-2021-02-25-dev"
          path: 'polkadot'  # should be the same as the one above
      - name: Summary
        run: |
          echo Summary:
          echo - version: ${{ steps.srtool_build.outputs.version }}
          echo - info: ${{ steps.srtool_build.outputs.info }}
          echo - json: ${{ steps.srtool_build.outputs.json }}
          echo - prop: ${{ steps.srtool_build.outputs.proposal_hash }}
  artifacts:
    needs: srtool
    runs-on: ubuntu-latest
    steps:
      - name: Store artifacts
        run: |
          echo TODO
  ipfs:
    needs: srtool
    runs-on: ubuntu-latest
    steps:
      - name: Seed WASM on IPFS
        run: |
          echo TODO
